/* groovylint-disable CompileStatic */
pipeline {
    agent any
    environment {
        DOCKER_CREDENTIALS_ID = 'DOCKER_1231866'
        DOCKER_IMAGE = 'lineem/1231866_devops_ca5'
        DOCKER_TAG = "${env.BUILD_ID}"
    }
    tools {
        'org.jenkinsci.plugins.docker.commons.tools.DockerTool' 'Docker'
    }
    stages {
        stage('Checkout') {
            steps {
                echo 'Checking Out...'
                script {
                    git branch: 'main',
                        url: 'https://github.com/line-em/devops-23-24-JPE-1231866.git'
                }
            }
        }
        stage('Assemble') {
            steps {
                dir('./CA2/Part2') {
                    echo 'Assembling...'
                    sh './gradlew assemble'
                }
            }
        }
        stage('Test') {
            steps {
                dir('./CA2/Part2') {
                    echo 'Testing...'
                    sh './gradlew test'
                }
            }
            post {
                always {
                    junit '**/build/test-results/**/*.xml'
                }
            }
        }
        stage('Javadoc') {
            steps {
                dir('./CA2/Part2') {
                    echo 'Generating Javadoc...'
                    sh './gradlew javadoc'
                }
            }
            post {
                always {
                    publishHTML([
                        allowMissing: false,
                        alwaysLinkToLastBuild: false,
                        keepAll: false,
                        reportDir: './CA2/Part2/build/docs/javadoc',
                        reportFiles: 'index.html',
                        reportName: 'Javadoc',
                        reportTitles: '',
                        useWrapperFileDirectly: true
                        ])
                }
            }
        }
        stage('Archive') {
            steps {
                echo 'Archiving...'
                archiveArtifacts artifacts: 'CA2/Part2/build/**/*.jar', onlyIfSuccessful: true
            }
        }
        stage('Create Dockerfile') {
            steps {
                script {
                    echo 'Creating Dockerfile...'
                    writeFile file: 'Dockerfile', text: """
                    FROM lineem/1231866_devops:ca4_part2_web
                    LABEL author="Aline Emily"
                    CMD [ "gradle", "bootRun" ]
                    """
                }
            }
        }
        stage('Deploy our image') {
            steps {
                script {
                    echo 'Building and publishing Docker image...'
                    docker.withTool('Docker'){
                        docker.withRegistry('https://index.docker.io/v1/', DOCKER_CREDENTIALS_ID ) {
                            def customImage = docker.build("${DOCKER_IMAGE}:${DOCKER_TAG}")
                            customImage.push()
                        }
                    }
                }
            }
        }
    }
}
