pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                echo 'Checking Out...'
                git 'https://github.com/line-em/devops-23-24-JPE-1231866'
            }
        }
        stage('Assemble') {
            steps {
                dir('CA2/Part1/gradle_basic_demo') {
                    echo 'Assembling...'
                    sh './gradlew assemble'
                }
            }
        }
        stage('Test') {
            steps {
                dir('CA2/Part1/gradle_basic_demo') {
                    echo 'Testing...'
                    sh './gradlew test'
                }
            }
                post {
                    junit '**/build/test-results/**/*.xml'
                }
        }
        stage('Archive') {
            steps {
                echo 'Archiving...'
                archiveArtifacts artifacts: 'CA2/Part1/gradle_basic_demo/build/libs/*.jar', onlyIfSuccessful: true
            }
        }
    }
}
